title: Microservices - How to Cook Microservices
email: alex@howtocookmicroservices.com
tag_line: Find out how to cook microservices with Ruby spices!
description: >
  This site is continuously updated collection of notes, 
  insights and ideas about building software platforms 
  empowered by microservices architecture using Ruby.

meta_description: >
  Site dedicated to all topics arount microservices and ruby / rails.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://howtocookmicroservices.com/" # the base hostname & protocol for your site
twitter_username: thaold
github_username:  thaold

# Build settings
markdown: kramdown
permalink: /:title/

collections:
  updates:
    output: false

gems:
  - jekyll-redirect-from